name: Terraform Lint & Plan

on:
  pull_request:
    - 'terraform/**'
    - '.github/workflows/**'

jobs:
  fmt-lint:
    name: Terraform fmt & validate
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
            terraform_wrapper: false

      - name: Terraform validate
        run: terraform init -backend=false && terraform valida
      - name: Terraform fmt (check)
        run: terraform fmt -check -recursive

  plan:
    name: Terraform plan
    needs: fmt-lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -no-color

      - name: Comment PR with plan
        if: ${{ github.event_name == 'pull_request' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: plan.out